stages:
  - deploy

before_script:
    # Before script: Set up SSH access
    - echo "Add SSH Private Key to Agent"
    - apk add --no-cache openssh-client
    - mkdir -p ~/.ssh && chmod 700 ~/.ssh
    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_ed25519
    - chmod 600 ~/.ssh/id_ed25519
    - ssh-keyscan -H 192.168.140.114 >> ~/.ssh/known_hosts

deploy:
  stage: deploy
  variables:
    GIT_STRATEGY: clone
  when: always # skip this stage on auto run
  script:
    # Copy the configuration to the NGINX server
    - echo "Copying local-conf to NGINX server..."
    - scp -r local-conf root@192.168.140.114:/tmp/

    # Test NGINX configuration
    - echo "Testing NGINX configuration..."
    - ssh root@192.168.140.114 'nginx -t'

    # Reload NGINX if configuration is valid
    - echo "Reloading NGINX..."
    - ssh root@192.168.140.114 'sudo nginx -s reload'    