stages:
  - deploy

#before_script:
    # Before script: Set up SSH access
#    - echo "Add SSH Private Key to Agent"
#    - apk add --no-cache openssh-client
#    - mkdir -p ~/.ssh && chmod 700 ~/.ssh
#    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_ed25519
#   - chmod 600 ~/.ssh/id_ed25519
#    - ssh-keyscan -H 192.168.140.114 >> ~/.ssh/known_hosts

deploy:
  stage: deploy
  variables:
    GIT_STRATEGY: clone
    NGINX_IPS: "192.168.140.114"
  when: always # skip this stage on auto run
  before_script:
    # Before script: Set up SSH access
    - echo "Add SSH Private Key to Agent"
    - apk add --no-cache openssh-client
    - mkdir -p ~/.ssh && chmod 700 ~/.ssh
    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_ed25519
    - chmod 600 ~/.ssh/id_ed25519
    
    # Adding SSH keys for all NGINX IPs to known hosts
    - for IP in $NGINX_IPS; do
        echo "Adding $IP to known_hosts";
        ssh-keyscan -H $IP >> ~/.ssh/known_hosts;
      done
  
  script:
    # Lặp qua từng IP trong biến NGINX_IPS
    - |
      for IP in $NGINX_IPS; do
          echo "[Info] Copy local-conf to $IP:/tmp/"

          # Tạo thư mục /tmp/waf-manager trên server từ xa
          ssh root@$IP "mkdir -p /tmp/waf-manager/"

          # Copy thư mục local-conf đến /tmp/waf-manager/
          scp -r local-conf root@$IP:/tmp/waf-manager/

          echo "[Info] Check condition requirements"
          # SSH vào IP để thực hiện các lệnh kiểm tra ban đầu và copy config
          ssh root@$IP << 'EOF'
            # Kiểm tra nginx có tồn tại hay không
            if ! command -v nginx &> /dev/null; then
                  echo "[Error] Nginx is not installed!"
                  exit 1
            fi

            # Kiểm tra thư mục /etc/nginx/modsec có tồn tại hay không
            if [ ! -d "/etc/nginx/modsec" ]; then
                  echo "[Error] Folder /etc/nginx/modsec not exist!"
                  exit 1
            fi

            echo "[Info] Backing up existing modsec configuration"
            # Remove old backup if it exists, then move existing files to backup
            rm -rf /tmp/waf-manager/modsec/*
            mv -f /etc/nginx/modsec/* /tmp/waf-manager/modsec/

            echo "[Info] Copying new config"
            # Remove existing contents in /etc/nginx/modsec before copying new files
            rm -rf /etc/nginx/modsec/*
            cp -rf /tmp/waf-manager/local-conf/* /etc/nginx/modsec/
      EOF

          echo "[Info] Test config and reload"
          # SSH vào IP để kiểm tra nginx config và xử lý theo kết quả
          ssh root@$IP << 'EOF'
            # Kiểm tra cấu hình nginx
            echo "[Info] Testing Nginx Config"
            if nginx -t; then
                  echo "[Info] Reloading Nginx"
                  # Nếu cấu hình hợp lệ, reload nginx
                  nginx -s reload
                  echo "[OK] Nginx reloaded successfully on $IP"
                  exit 0
            else
                  # If config is invalid, restore backup
                  rm -rf /etc/nginx/modsec/*
                  cp -rf /tmp/waf-manager/modsec/* /etc/nginx/modsec/
                  echo "[Error] Restored previous modsec configuration due to config test failure!"
                  exit 1
            fi
      EOF

      done


